name: 'Tests: node.js (0.x)'

on: [pull_request, push]

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      stable: ${{ steps.set-matrix.outputs.requireds }}
      unstable: ${{ steps.set-matrix.outputs.optionals }}
    steps:
      - uses: ljharb/actions/node/matrix@main
        id: set-matrix
        with:
          preset: '0.x'

  stable:
    needs: [matrix]
    name: 'stable minors'
    runs-on: ubuntu-latest

    strategy:
      matrix: ${{ fromJson(needs.matrix.outputs.stable) }}

    steps:
      - uses: actions/checkout@v2
      - uses: ljharb/actions/node/install@main
        name: 'nvm install ${{ matrix.node-version }} && npm install'
        with:
          node-version: ${{ matrix.node-version }}
          cache-node-modules-key: node_modules-${{ github.workflow }}-${{ github.action }}-${{ github.run_id }}
          skip-ls-check: true
      - run: npm run tests-only
      - run: bash <(curl -s https://codecov.io/bash) -f coverage/*.json;

  unstable:
    needs: [matrix, stable]
    name: 'unstable minors'
    continue-on-error: true
    if: ${{ !github.head_ref || !startsWith(github.head_ref, 'renovate') }}
    runs-on: ubuntu-latest

    strategy:
      matrix: ${{ fromJson(needs.matrix.outputs.unstable) }}

    steps:
      - uses: actions/checkout@v2
      - uses: ljharb/actions/node/install@main
        name: 'nvm install ${{ matrix.node-version }} && npm install'
        with:
          node-version: ${{ matrix.node-version }}
          cache-node-modules-key: node_modules-${{ github.workflow }}-${{ github.action }}-${{ github.run_id }}
          skip-ls-check: true
      - run: npm run tests-only
        if: ${{ matrix.node-version }} != 0.6
      - run: ./node_modules/.bin/tape 'test/**/*.js'
        if: ${{ matrix.node-version }} = 0.6
      - run: bash <(curl -s https://codecov.io/bash) -f coverage/*.json;
        if: ${{ matrix.node-version }} != 0.6

  node:
    name: 'node 0.x'
    needs: [stable, unstable]
    runs-on: ubuntu-latest
    steps:
      - run: 'echo tests completed'
